<template>
  <div class="modal-backdrop" @click="$emit('close')">
    <div class="modal-content" @click.stop>
      <div class="modal-header">
        <h3>📊 Confidence Score Explanation</h3>
        <button @click="$emit('close')" class="close-btn">&times;</button>
      </div>
      
      <div class="modal-body">
        <!-- What is Confidence Score -->
        <div class="explanation-section">
          <h4>🤖 What is the Confidence Score?</h4>
          <p>
            The confidence score represents the AI model's certainty about threat classification. 
            It's generated by our <strong>HierarchicalTransformerIDS</strong> neural network that 
            analyzes <strong>77 network traffic features</strong> to identify security threats.
          </p>
          
          <!-- Mathematical Formula -->
          <div class="formula-section">
            <h5>📐 Mathematical Formula</h5>
            <div class="formula-container">
              <div class="formula-main">
                Confidence(x) = σ(W<sub>2</sub> · ReLU(W<sub>1</sub> · x + b<sub>1</sub>) + b<sub>2</sub>)
              </div>
              <div class="formula-breakdown">
                <div class="formula-item">
                  <span class="variable">x</span> = 77-dimensional feature vector from network traffic
                </div>
                <div class="formula-item">
                  <span class="variable">W<sub>1</sub>, W<sub>2</sub></span> = Learned weight matrices from training
                </div>
                <div class="formula-item">
                  <span class="variable">b<sub>1</sub>, b<sub>2</sub></span> = Bias vectors
                </div>
                <div class="formula-item">
                  <span class="variable">ReLU</span> = Rectified Linear Unit activation function
                </div>
                <div class="formula-item">
                  <span class="variable">σ</span> = Sigmoid function → outputs probability [0, 1]
                </div>
              </div>
            </div>
          </div>
          
          <div class="model-info">
            <div class="info-item">
              <span class="label">Model Architecture:</span>
              <span class="value">Hierarchical Transformer with Binary & Multi-class Stages</span>
            </div>
            <div class="info-item">
              <span class="label">Input Features:</span>
              <span class="value">77 selected network traffic characteristics</span>
            </div>
            <div class="info-item">
              <span class="label">Accuracy:</span>
              <span class="value">99.30% Binary | 98.90% Multi-class</span>
            </div>
          </div>
        </div>

        <!-- Response Thresholds -->
        <div class="explanation-section">
          <h4>⚡ Response Thresholds</h4>
          <p>Based on the confidence level, the system automatically decides the appropriate response:</p>
          
          <div class="thresholds-container">
            <div class="threshold-item high-confidence">
              <div class="threshold-header">
                <div class="threshold-range">&gt; 90%</div>
                <div class="threshold-label">Automatic Response</div>
              </div>
              <div class="threshold-description">
                🚨 <strong>Immediate Action:</strong> High confidence threats are automatically blocked and logged. 
                The system is highly certain this is a genuine security threat.
              </div>
            </div>

            <div class="threshold-item medium-high-confidence">
              <div class="threshold-header">
                <div class="threshold-range">80% - 90%</div>
                <div class="threshold-label">Auto-create Proposal</div>
              </div>
              <div class="threshold-description">
                📋 <strong>Manager Review:</strong> System automatically creates a proposal for Manager approval. 
                High likelihood of threat but requires human validation.
              </div>
            </div>

            <div class="threshold-item medium-confidence">
              <div class="threshold-header">
                <div class="threshold-range">70% - 80%</div>
                <div class="threshold-label">Manual Decision Alert</div>
              </div>
              <div class="threshold-description">
                ⚠️ <strong>Operator Decision:</strong> Alert sent to security operators who can manually 
                create proposals if needed. Requires human judgment.
              </div>
            </div>

            <div class="threshold-item low-confidence">
              <div class="threshold-header">
                <div class="threshold-range">&lt; 70%</div>
                <div class="threshold-label">Silent Logging</div>
              </div>
              <div class="threshold-description">
                📝 <strong>Background Monitoring:</strong> Low confidence events are logged for analysis 
                but no immediate action is taken.
              </div>
            </div>
          </div>
        </div>

        <!-- Examples -->
        <div class="explanation-section">
          <h4>💡 Confidence Score Examples</h4>
          <div class="examples-container">
            <div class="example-item">
              <div class="example-score confidence-high">95.2%</div>
              <div class="example-text">
                <strong>DDoS Attack:</strong> Clear attack pattern with overwhelming traffic volume. 
                Model is highly certain - immediate blocking activated.
              </div>
            </div>
            <div class="example-item">
              <div class="example-score confidence-medium-high">87.1%</div>
              <div class="example-text">
                <strong>Brute Force:</strong> Suspicious login patterns detected. 
                High probability but needs Manager approval before blocking.
              </div>
            </div>
            <div class="example-item">
              <div class="example-score confidence-medium">74.3%</div>
              <div class="example-text">
                <strong>Port Scan:</strong> Unusual port activity detected. 
                Operator should investigate and decide if action is needed.
              </div>
            </div>
          </div>
        </div>

        <!-- Technical Details -->
        <div class="explanation-section">
          <h4>🔧 Technical Details</h4>
          <div class="technical-grid">
            <div class="tech-item">
              <div class="tech-label">Feature Analysis</div>
              <div class="tech-value">77 network traffic characteristics including packet sizes, timing, protocols, and flow patterns</div>
            </div>
            <div class="tech-item">
              <div class="tech-label">Model Training</div>
              <div class="tech-value">Trained on CIC-IDS2017 dataset with real-world attack scenarios</div>
            </div>
            <div class="tech-item">
              <div class="tech-label">Output Format</div>
              <div class="tech-value">Probability score (0-1) converted to percentage for display</div>
            </div>
            <div class="tech-item">
              <div class="tech-label">Update Frequency</div>
              <div class="tech-value">Real-time analysis of incoming network traffic</div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="modal-footer">
        <button @click="$emit('close')" class="btn btn-primary">
          Got it!
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
// Emit close event
defineEmits(['close'])
</script>

<style scoped>
.modal-backdrop {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  border-radius: 8px;
  width: 90%;
  max-width: 800px;
  max-height: 90vh;
  overflow-y: auto;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.5rem 2rem 1rem;
  border-bottom: 1px solid #e0e0e0;
}

.modal-header h3 {
  margin: 0;
  color: #2c3e50;
  font-size: 1.5rem;
}

.close-btn {
  background: none;
  border: none;
  font-size: 2rem;
  cursor: pointer;
  color: #7f8c8d;
  line-height: 1;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-btn:hover {
  color: #2c3e50;
}

.modal-body {
  padding: 2rem;
}

.explanation-section {
  margin-bottom: 2rem;
}

.explanation-section h4 {
  margin: 0 0 1rem 0;
  color: #34495e;
  font-size: 1.2rem;
  border-bottom: 2px solid #3498db;
  padding-bottom: 0.5rem;
}

.explanation-section p {
  margin: 0 0 1rem 0;
  color: #555;
  line-height: 1.6;
}

/* Model Info */
.model-info {
  background-color: #f8f9fa;
  border-radius: 6px;
  padding: 1rem;
  margin-top: 1rem;
}

.info-item {
  display: flex;
  margin-bottom: 0.5rem;
}

.info-item:last-child {
  margin-bottom: 0;
}

.info-item .label {
  font-weight: 600;
  color: #2c3e50;
  min-width: 140px;
}

.info-item .value {
  color: #555;
}

/* Formula Section */
.formula-section {
  background: linear-gradient(135deg, #e3f2fd, #f8f9fa);
  border-radius: 8px;
  padding: 1.5rem;
  margin: 1.5rem 0;
  border-left: 4px solid #2196f3;
}

.formula-section h5 {
  margin: 0 0 1rem 0;
  color: #1976d2;
  font-size: 1.1rem;
}

.formula-container {
  text-align: center;
}

.formula-main {
  font-family: 'Courier New', 'Times New Roman', monospace;
  font-size: 1.3rem;
  font-weight: bold;
  color: #1565c0;
  background: white;
  padding: 1rem;
  border-radius: 6px;
  margin-bottom: 1rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  border: 1px solid #e1f5fe;
}

.formula-breakdown {
  text-align: left;
  margin-top: 1rem;
}

.formula-item {
  display: flex;
  align-items: center;
  margin-bottom: 0.5rem;
  font-size: 0.9rem;
  color: #37474f;
}

.formula-item:last-child {
  margin-bottom: 0;
}

.variable {
  font-family: 'Courier New', monospace;
  font-weight: bold;
  color: #1976d2;
  background: rgba(33, 150, 243, 0.1);
  padding: 0.2rem 0.4rem;
  border-radius: 3px;
  margin-right: 0.5rem;
  min-width: 60px;
  text-align: center;
}

/* Thresholds */
.thresholds-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.threshold-item {
  border: 2px solid;
  border-radius: 8px;
  padding: 1rem;
}

.threshold-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
}

.threshold-range {
  font-weight: bold;
  font-size: 1.1rem;
}

.threshold-label {
  font-weight: 600;
  text-transform: uppercase;
  font-size: 0.9rem;
}

.threshold-description {
  color: #555;
  line-height: 1.5;
}

.high-confidence {
  border-color: #e74c3c;
  background-color: #fdf2f2;
}

.high-confidence .threshold-range,
.high-confidence .threshold-label {
  color: #e74c3c;
}

.medium-high-confidence {
  border-color: #3498db;
  background-color: #f4f8fc;
}

.medium-high-confidence .threshold-range,
.medium-high-confidence .threshold-label {
  color: #3498db;
}

.medium-confidence {
  border-color: #f39c12;
  background-color: #fdf9f0;
}

.medium-confidence .threshold-range,
.medium-confidence .threshold-label {
  color: #f39c12;
}

.low-confidence {
  border-color: #95a5a6;
  background-color: #f8f9fa;
}

.low-confidence .threshold-range,
.low-confidence .threshold-label {
  color: #95a5a6;
}

/* Examples */
.examples-container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.example-item {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem;
  background-color: #f8f9fa;
  border-radius: 6px;
}

.example-score {
  font-weight: bold;
  font-size: 1.2rem;
  padding: 0.5rem;
  border-radius: 4px;
  min-width: 60px;
  text-align: center;
}

.example-score.confidence-high {
  background-color: #fee;
  color: #e74c3c;
}

.example-score.confidence-medium-high {
  background-color: #f4f8fc;
  color: #3498db;
}

.example-score.confidence-medium {
  background-color: #fdf9f0;
  color: #f39c12;
}

.example-text {
  flex: 1;
  line-height: 1.5;
  color: #555;
}

.example-text strong {
  color: #2c3e50;
}

/* Technical Details */
.technical-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1rem;
}

.tech-item {
  padding: 1rem;
  background-color: #f8f9fa;
  border-radius: 6px;
}

.tech-label {
  font-weight: 600;
  color: #2c3e50;
  margin-bottom: 0.5rem;
}

.tech-value {
  color: #555;
  line-height: 1.5;
}

.modal-footer {
  padding: 1rem 2rem 1.5rem;
  border-top: 1px solid #e0e0e0;
  display: flex;
  justify-content: flex-end;
}

/* Responsive */
@media (max-width: 768px) {
  .modal-content {
    width: 95%;
    margin: 1rem;
  }
  
  .modal-header,
  .modal-body,
  .modal-footer {
    padding-left: 1rem;
    padding-right: 1rem;
  }
  
  .threshold-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 0.5rem;
  }
  
  .example-item {
    flex-direction: column;
    align-items: flex-start;
    text-align: left;
  }
}</style>